/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormControl: typeof import('./components/FormControl.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LikertOption: typeof import('./components/LikertOption.vue')['default']
    LikertOptionGroup: typeof import('./components/LikertOptionGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Survey: typeof import('./components/Survey.vue')['default']
    Textarea: typeof import('./components/Textarea.vue')['default']
  }
}
